**QUESTION 1**
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


**QUESTION 2**
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [ ]:
arr1,arr2=(list(map(int,input().split()))for i in range (2))
arr1=np.array(arr1)
arr2=np.array(arr2)
print(np.concatenate((arr1,arr2)))
print(np.sort(np.concatenate((arr1,arr2))))

2 1 3
5 4 6
[2 1 3 5 4 6]
[1 2 3 4 5 6]


**QUESTION 3**
Write a code snippet to find the dimensions of a ndarray and its size.

In [9]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr1.shape)
print(arr1.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


**QUESTION 4**
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [11]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1.shape)
print(arr1.ndim)
arr2=np.reshape(arr1,(3,3))
print(arr2.shape)
print(arr2.ndim)

(9,)
1
(3, 3)
2


**QUESTION 5**
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [20]:
#Considering two square numpy arrays
arr1=np.array([[1,3],[4,6]])
arr2=np.array([[2,6],[7,9]])
print(arr1)
print(arr2)
print()
#stacking both the matrices vertically
print(np.vstack((arr1,arr2)))
print()
#stacking both the matrices horizontally
print(np.hstack((arr1,arr2)))


[[1 3]
 [4 6]]
[[2 6]
 [7 9]]

[[1 3]
 [4 6]
 [2 6]
 [7 9]]

[[1 3 2 6]
 [4 6 7 9]]


**QUESTION 6**
How to get unique items and counts of unique items?

In [21]:
list1 = [1,3,1,5,2,4]
list1 = list(set(list1))
print(list1)
print()
print(len(list1))

[1, 2, 3, 4, 5]

5
